// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package boostrap

import (
	config2 "garavel/config"
	"garavel/initialize"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// init application.
func InitializeApp(system *config2.System, logger *zap.Logger) (*App, error) {
	engine := initialize.Routers()
	server := initServer(system, engine)
	app := newApp(system, logger, server)
	return app, nil
}
