// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"garavel/config"
	"garavel/initialize"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitializeApp(server *config.Server, logger *zap.Logger) (*App, error) {
	engine := initialize.Routers()
	server2 := httpServer(server, engine)
	app := newApp(server, logger, server2)
	return app, nil
}
